# Formatter configuration, shared by `nix fmt` and `nix flake check`.
{ pkgs, ... }:
{
  projectRootFile = "flake.nix";

  # Rust: the same rustfmt CI enforces via `cargo fmt --check`.
  programs.rustfmt = {
    enable = true;
    edition = "2021";
  };

  # Nix: formats flake.nix and this file.
  programs.nixfmt.enable = true;

  # Markdown: markdownlint-cli2 fixes what is mechanically fixable and fails on
  # the rest, so it serves as both formatter and linter. Rules live in
  # .markdownlint-cli2.jsonc; the excludes below mirror that file's `ignores`,
  # because treefmt passes paths explicitly and config-level ignores only apply
  # to globs markdownlint-cli2 expands itself.
  settings.formatter.markdownlint = {
    command = "${pkgs.markdownlint-cli2}/bin/markdownlint-cli2";
    options = [ "--fix" ];
    includes = [ "*.md" ];
    excludes = [
      # Generated by release-plz from commit messages.
      "CHANGELOG.md"
      # Schemas are a DSL: semantic indentation, `<? … ?>` inline HTML.
      "*.schema.md"
      # Generated by `render` and held to byte equality by the example. Fixing
      # it in place would paper over a renderer regression; CI still *lints* it
      # (it is not in .markdownlint-cli2.jsonc's ignores), it is only never
      # rewritten here.
      "examples/*.md"
    ];
  };
}
